### ISSUE TITLE
Setup K8S Cluster With KOPS

### ISSUE THREAD

**Issue by vladimir-ilyashenko** [DigitallyInspiredLearn/digitallyinspired-todo-deployment#11]
We need k8s cluster setup using kops, Follow instructions at https://github.com/kubernetes/kops/blob/master/docs/aws.md
- [x] For DNS follow [scenario 1a](https://github.com/kubernetes/kops/blob/master/docs/aws.md#scenario-1a-a-domain-purchasedhosted-via-aws). 
- [x] Use eu-west-1 region for S3 bucket
- [x] Configure cluster to use [existing VPC](https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md)
- [x] Configure cluster to use [NAT on EC2](https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md#shared-nat-egress)

**Comment by IliaUkhov** [comment]
Which our subnets may I use for cluster setup in the last task?
