### ISSUE TITLE
Setup Jenkins Master

### ISSUE THREAD

**Issue by vladimir-ilyashenko** [DigitallyInspiredLearn/digitallyinspired-todo-deployment#6]
We need install jenkins master on 10.142.1.5 machine. Install it from OS packages (non-docker),

**Comment by vladimir-ilyashenko** [comment]
@Julisel please document details at [documentation](https://github.com/DigitallyInspiredLearn/digitallyinspired-todo-deployment/blob/master/documentation/infrastructure/jenkins.md)

**Comment by Julisel** [comment]
All was documented
