### ISSUE TITLE
Setup Route53 Zone

### ISSUE THREAD

**Issue by vladimir-ilyashenko** [DigitallyInspiredLearn/digitallyinspired-todo-deployment#7]
We need private zone in route53 in order to serve as k8s DNS:
- [ ] Create k8s.learn.digitallyinspired.com private hosted zone in route53.
- [ ] Configure DI DNS server to redirect queries to this domain to VPC DNS server (10.142.0.2)

**Comment by ANitsulenko** [comment]
Declined.
Please do not take any actions until reasons will be clarified
