### ISSUE TITLE
Create K8S Configurations for Backend

### ISSUE THREAD

**Issue by vladimir-ilyashenko** [DigitallyInspiredLearn/digitallyinspired-todo-deployment#9]
- [x] Create [secret](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#secret-v1-core) containing application's config file
- [x] Create [deployment](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#deployment-v1-apps). It should mount a secret.
- [x] Create [service](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#service-v1-core)
- [x] Create [ingress](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#ingress-v1beta1-extensions)

**Comment by AndreyPlachinda** [comment]
There was a problem with mysql deploy, using the secret.
Used as an example guides:

https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

https://kubernetes.io/docs/concepts/configuration/secret/

I use the secret. with kubectl describe pod <my pod> the following error:
Warning Failed 6m38s (x12 over 8m50s) kubelet, ip-10-142-33-35.eu-west-1.compute.internal Error: Couldn't find key mysql-database in Secret default / db-credentials

If I specify the parameters for the database directly in the deployment file, then the pod works and all OK

**Comment by AndreyPlachinda** [comment]
Fix: to create a secret from the yaml file, use the command:

kubectl create -f <my_secret> .yaml

I used the command to create a secret from the  txt files:

kubectl create secret generic db-credentials --from-file =. / <my_file> .txt
